### PR TITLE
Meta data

### PR DESCRIPTION
**Pull request by bhaney**
Adds the meta.json file to PaperSubmit and IPFS uploading. Right now only adds authors, title, abstract, and the contract address.

### CODE REVIEW

**Comment by mistry** [comment]
Looks reasonable, I want to go through and test some thing with you tomorrow before merging.

**Comment by SaulAryehKohn** [comment]
Looks like we need to adapt our coveralls requirements for merge... @mistry I'll defer to your testing on this one.

**Comment by SaulAryehKohn** [comment]
FYI, Coveralls settings can be found [here](https://coveralls.io/github/arXain/arXain/settings). I'm going to set the coverage threshold for failure to 60% (we can bring it up as testing increases) and decrease for failure to -5% (arbitrary, but I think it's reasonable).

**Comment by david-hopper** [comment]
I got an error when running `truffle compile && truffle migrate`.  However, submitting a paper and revisions all seem to go fine, I've copied the error below just in case.

I can submit multiple revisions of a paper, and view their status with the check status page just fine. meta.json is included as well.
```
Compiling ./contracts/Comments.sol...
Writing artifacts to ./build/contracts

Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x93011cdc4ea356e3952b7ea31760d40493b2fea0241282801196b4148c90442d
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving successful migration to network...
  ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Paper...
  ... 0xa3211b097bd641b922022dc9705dc418ea754b8078d037aefb3353781cdb3e29
  Paper: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
  Deploying Comments...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Comments contract constructor expected 1 arguments, received 0
    at /Users/davidhopper/.npm-packages/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:388:1
    at new Promise (<anonymous>)
    at /Users/davidhopper/.npm-packages/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:372:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by mistry** [comment]
Can you try removing your contract json files and redoing the compile/migrate?

**Comment by bhaney** [comment]
There is a feature in AmendContract that between Step 2, when you upload your revision to IPFS, and step 3, where you submit your revision to the blockchain, where you can press "Submit to IPFS" multiple times and keep on incrementing your version directories in IPFS.

The submission to the blockchain will only pick up the revision for v2, but you will still have all the other directories in your IPFS directory. I will try to add a check on the front-end to make it so that you cannot submit a new revision to IPFS if you've already sent one and not yet updated the blockchain, but front-end checks are easy to by-pass. It may make sense to also have some kind of check on the flask side.

**Comment by mistry** [comment]
Also @david-hopper I get this error when accessing site: I am folllowing instructions on setting up ipfs correctly I think and everything installs fine and is setup. IPFS connection not working either (on site)

`127.0.0.1 - - [28/Feb/2018 19:18:24] "GET /init/arxain HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kmistry/Khilesh_projects/arXain/node_client/node/node/__init__.py", line 1, in <module>
    from .node import app
  File "/home/kmistry/Khilesh_projects/arXain/node_client/node/node/node.py", line 5, in <module>
    from pyXain import pyXain
  File "/home/kmistry/Khilesh_projects/arXain/node_client/pyXain/pyXain/__init__.py", line 1, in <module>
    from pyXain.pyXain import pyXain
ImportError: No module named pyXain
vi /home/kmistry/Khilesh_projects/arXain/node_client/node/node/__init__.py
`

I think its an ubuntu path thing or maybe I'm using wrong python somehow

**Comment by bhaney** [comment]
I've edited SubmitPaper and AmendPaper in order to make it harder for people to accidentally submit multiple files to IPFS or the blockchain. The submission steps are split up over a few pages now, instead of having one giant form with multiple steps.

**Pull request merged**
